APPLICATION_NAME = VCamFree

VCamFree_FILES = VCFAppDelegate.m VCFMainViewController.m VCFMediaStore.m
VCamFree_CFLAGS = -fobjc-arc
VCamFree_FRAMEWORKS = UIKit Foundation CoreGraphics AVFoundation PhotosUI MobileCoreServices
VCamFree_CODESIGN_FLAGS = -Sentitlements.plist
VCamFree_INSTALL_PATH = /Applications

include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/application.mk
