LIBRARY_NAME = VCFOverlay

VCFOverlay_FILES = VCFOverlay.xm VCFAdjustments.m \
    ../Core/VCFPaths.m ../Core/VCFSettings.m
VCFOverlay_CFLAGS = -fobjc-arc -I../Core
VCFOverlay_FRAMEWORKS = UIKit CoreGraphics Foundation CoreFoundation
VCFOverlay_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries

include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/library.mk
